QUEUE:
  PLAYER_ONLY: '&5&lQUEUE &8&l» &cQuesto commando puo essere eseguito solo dai giocatori.'
  SPECIFY_SERVER: '&5&lQUEUE &8&l» &cPerfavore specifica un server. Usa: &a/joinqueue <server>'
  ALREADY_IN_QUEUE: '&5&lQUEUE &8&l» &cSei gia in coda per il &e{server}&c.'
  JOINED_QUEUE: '&5&lQUEUE &8&l» &aSei entrato in coda per il &e{server} &7(Posiione: &e{position}&7).'
  LEFT_QUEUE: '&5&lQUEUE &8&l» &aSei uscito dalla coda per il &e{server}&a.'
  FULL_QUEUE: '&5&lQUEUE &8&l» &cLa coda per il &e{server} &ce attualmente piena. Perfavore riprova
    piu tardi.'
  NOT_IN_QUEUE: '&5&lQUEUE &8&l» &cNon sei in coda per il  &e{server}&c.'
  ERROR_OCCURRED: '&5&lQUEUE &8&l» &cSi e verificato un problema durante questa operazione perfavore
    contatta un developer.'
  QUEUE_PAUSED: '&5&lQUEUE &8&l» &cLa coda per il  &e{server} &ce attualmente in pausa. Perfavore
    riprova piu tardi.'
  QUEUE_RESUMED: '&5&lQUEUE &8&l» &7La coda per il &e{server} &7è stata ripristinata.'
  YOU_WILL_BE_MOVED_SOON: '&5&lQUEUE &8&l» &7Sarai spostato al &e{server} &7a breve. Attendere prego...'
  QUEUE_STOPPED_SUCCESS: '&5&lQUEUE &8&l» &7La coda per il &e{server} &7è stata stoppata con successo.'
